version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    container_name: node_app
    restart: unless-stopped


